### ISSUE TITLE
Bug - Checking for weak consistency

### ISSUE THREAD

**Issue by menesro** [michael-emmi/violat#7]
I noticed that the check for weak consistency seems to be broken in the current version (1.0.11). Running violat on ConcurrentHashMap (the .json specification in the repository) I get the following:

violat-validator resources/specs/java/util/concurrent/ConcurrentHashMap.json  
violat version 1.0.11
---
Unhandled promise rejection:
TypeError: Cannot read property 'id' of undefined
    at VisibilityImpl.isVisible (/usr/local/lib/node_modules/violat/src/core/visibility.ts:186:4)
    at VisibilityExtender.missingLink (/usr/local/lib/node_modules/violat/src/core/visibility.ts:326:7)
    at VisibilityExtender.extend (/usr/local/lib/node_modules/violat/src/core/visibility.ts:308:22)
    at VisibilityExtender.getExtensions (/usr/local/lib/node_modules/violat/src/core/visibility.ts:268:23)
    at getExtensions.next (<anonymous>)
    at VisibilityGenerator.getVisibilities (/usr/local/lib/node_modules/violat/src/core/visibility.ts:164:20)
    at getVisibilities.next (<anonymous>)
    at RelaxedExecutionGenerator.getExecutions (/usr/local/lib/node_modules/violat/src/core/execution.ts:77:22)
    at getExecutions.next (<anonymous>)
    at OutcomePredictor.outcomes (/usr/local/lib/node_modules/violat/src/search/prediction.ts:26:20)
    at outcomes.next (<anonymous>)
    at StaticOutcomesTester.getViolations (/usr/local/lib/node_modules/violat/src/alg/testing.ts:45:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at RandomTestValidator.getViolations (/usr/local/lib/node_modules/violat/src/alg/validation.ts:63:22)
    at main (/usr/local/lib/node_modules/violat/src/cli/validator.ts:112:20)

Modifying the ConcurrentHashMap.json such that all visibilities are complete, this error doesn’t show up anymore.

**Comment by alaukiknpant** [comment]
@michael-emmi 

I get the same error:

```
violat-validator LinkedBlockingQueue.json               
violat version 1.0.16
---
Unhandled promise rejection:
RangeError: Chance: No valid entries in array weights
    at Chance.weighted (/usr/local/lib/node_modules/violat/node_modules/chance/chance.js:740:19)
    at SingleUseRandomProgramGenerator.getMethod (/usr/local/lib/node_modules/violat/src/enumeration/random.ts:159:24)
    at SingleUseRandomProgramGenerator.getInvocation (/usr/local/lib/node_modules/violat/src/enumeration/random.ts:151:23)
    at /usr/local/lib/node_modules/violat/src/enumeration/random.ts:143:77
    at Array.map (<anonymous>)
    at SingleUseRandomProgramGenerator.getSequence (/usr/local/lib/node_modules/violat/src/enumeration/random.ts:143:63)
    at /usr/local/lib/node_modules/violat/src/enumeration/random.ts:126:65
    at Array.map (<anonymous>)
    at SingleUseRandomProgramGenerator.getProgram (/usr/local/lib/node_modules/violat/src/enumeration/random.ts:126:51)
    at RandomProgramGenerator.getProgram (/usr/local/lib/node_modules/violat/src/enumeration/random.ts:79:40)
    at RandomProgramGenerator.getPrograms (/usr/local/lib/node_modules/violat/src/enumeration/random.ts:65:26)
    at getPrograms.next (<anonymous>)
    at RandomTestValidator.getPrograms (/usr/local/lib/node_modules/violat/src/alg/validation.ts:85:14)
    at getPrograms.next (<anonymous>)
    at Object.batch (/usr/local/lib/node_modules/violat/src/enumeration/batch.ts:4:12)
    at batch.next (<anonymous>)
```

What was the issue with the problem mentioned above? I am using version 1.0.16

**Comment by michael-emmi** [comment]
Hi @alaukiknpant is this with the same spec provided in the repository? Have you edited the spec?

Here’s what I see:
```
% violat-validator resources/specs/java/util/concurrent/LinkedBlockingQueue.json
violat version 1.0.16
---
Found 0 violations.
```

**Comment by alaukiknpant** [comment]
@michael-emmi I suspect that the problem might be with my Java Pathfinder then because all other requirements are fulfilled.

Is there any way I can validate that my installation is correct for Java Pathfinder so that Violat Works. Alternatively, is there a Dockerfile I can use to build an environment required for Violat? I understand that you can configure Java Pathfinder in many ways depending on your needs, but I'm not sure if I did it correctly for Violat.

I would also be happy to post a Dockerfile if I manage to find out what's wrong.

Thanks for your reply!

**Comment by michael-emmi** [comment]
@alaukiknpant unless you’re running with different arguments than what you’re showing, I don’t think that Java Pathfinder could have anything to do with it. Unless you specify another `--tester` argument, Violat uses JCStress as a backend, not JPF.

We do not currently have any Docker (or similar) containers for Violat.

Also, since your error:
```
RangeError: Chance: No valid entries in array weights
```
is clearly different than the one with which this (closed) issue was created:
```
TypeError: Cannot read property 'id' of undefined
```
it would be better to open a new issue for this.

**Comment by alaukiknpant** [comment]
Thank you @michael-emmi!

Got it, I will create a new issue for this. I updated the requirements and violat started working for LinkedBlockingQueue.json. However, I still get the same error for  PriorityBlockingQueue.json. I will just create a new issue with all the details of my system so that we can move the discussion there.
